### PR TITLE
#37 improve localization algorithm

### PR DESCRIPTION
**Pull request by tomvanswam**
5 New translation strings added to facilitate correctly building a sentence in another language. 
```
"primary entity description": "Direction Entity",
"secondary entity description": "Secondary Entity",
"language description": "Direction Abbreviation Language",
"offset description": "Direction Offset",
"show north description": "Show North Indicator"
```

### CODE REVIEW

**Comment by tomvanswam** [comment]
@woodcat64, @andilge, @rainer-geiger, @matteofranceschini, @hwikene, @porebas and @artemyevav
Would you be so kind to help translate the 5 new strings?

You can comment the translation to this PR, or add the code to the JSON and create a PR to the `#37 improve localization algorithm` branch

**Comment by andilge** [comment]
sure, pls follow this for fr, pt and es

pt
"primary entity description": "Entidade primária",
"secondary entity description": "Entidade secundária",
"language description": "Idioma abreviação de direção",
"offset description": "Offset de direção",
"show north description": "Mostrar o indicador norte"

fr
"primary entity description": "Entité primaire",
"secondary entity description": "Entité secondaire",
"language description": "Langue abréviation de la direction",
"offset description": "Décalage de la direction",
"show north description": "Afficher l'indicateur du nord"

es
"primary entity description": "Entidad primaria",
"secondary entity description": "Entidad secundaria",
"language description": "Idioma abreviatura dirección",
"offset description": "Desplazamiento de la dirección",
"show north description": "Mostrar indicador del norte"

**Comment by andilge** [comment]
If Rainer is taking longer than you want to wait, here German

de
"primary entity description": "Entität Richtung",
"secondary entity description": "Sekundäre Entität",
"language description": "Sprache Abkürzungen Richtung",
"offset description": "Richtungsversatz",
"show north description": "Nord-Indikator anzeigen"

**Comment by artemyevav** [comment]
ru
"primary entity description": "Объект направления",
"secondary entity description": "Дополнительный объект",
"language description": "Язык аббревиатуры направления",
"offset description": "Смещение направления",
"show north description": "Показать индикатор севера"

**Comment by Woodcat64** [comment]
cz
"primary entity description": "Entita směru ",
"secondary entity description": "Sekundární entita",
"language description": "Jazyk zkratky směru",
"offset description": "Kompenzace směru",
"show north description": "Zobrazit indikátor severu"

**Comment by artemyevav** [comment]
> "language description": "Sprache Abkürzungen Richtung",

`Richtungsabkürzungssprache` ?

**Comment by porebas** [comment]
pl
"primary entity description": "Encja Kierunku",
"secondary entity description": "Encja Dodatkowa",
"language description": "Język Skrótów Kierunków",
"offset description": "Przesunięcie Kierunku",
"show north description": "Pokaż Wskaźnik Północy"

**Comment by andilge** [comment]
I prefer not to translate
_Richtungsabkürzungssprache_
which is a  "holperiges Spaghettiwort".

**Comment by rainer-geiger** [comment]
> If Rainer is taking longer than you want to wait, here German
> 
> de
> "primary entity description": "Entität Richtung",
> "secondary entity description": "Sekundäre Entität",
> "language description": "Sprache Abkürzungen Richtung",
> "offset description": "Richtungsversatz",
> "show north description": "Nord-Indikator anzeigen"

Thank you @andilge for your translation, I took the liberty of making minor adjustments ;-)

"primary entity description": "Richtungsentität",
"secondary entity description": "Sekundäre Entität",
"language description": "Sprache der Himmelsrichtung",
"offset description": "Richtungsversatz",
"show north description": "Nord-Indikator anzeigen"

**Comment by tomvanswam** [comment]
Wow you guys are fast!

**Comment by hwikene** [comment]
no
"primary entity description": "Retningsenhet",
"secondary entity description": "Sekundær enhet",
"language description": "Retning Forkortelse Språk",
"offset description": "Retningsforskyvningt",
"show north description": "Vis nordindikator"

**Comment by matteofranceschini** [comment]
IT

"primary entity description": "Entità primaria",
"secondary entity description": "Entità secondaria",
"language description": "Lingua abbreviazione direzione",
"offset description": "Compensazione direzione",
"show north description": "Mostra indicatore Nord"

**Pull request merged**
