### PR TITLE
v0.3.1

### PR DESCRIPTION
**Pull request by tomvanswam**
Add Norwegian translation, thanks to @hwikene
Add Portugese translation, thanks to @andilge #27 
Add Spanish translation, thanks to @andilge #27
Add French translation, thanks to @andilge #27
Improve README on how to configure abbreviation language #27
Fix incorrect default indicator (did not match default from README)

### CODE REVIEW

**Comment by tomvanswam** [comment]
@dhover Could you have a look at the README.md and let me know if you think it's more clear now on how to configure a language?

**Comment by dhover** [comment]
@tomvanswam The README.cmd is excellent now. I think it is clear now how to configure a language. You also added a column Supported so it is clear from which version the language is being supported or not.
Good work!

**Comment by dhover** [comment]
One small question: The README.cmd on github is now ok but the README in Home Assistant is still the old one. After the install of version 0.3.0 I've restarted Home Assistant. I am using HACS. To get the README I press on the menu and choose Information.
Is this something like caching or so?

**Comment by tomvanswam** [comment]
When I merge this pull request, the README in the master branch will be updated, after that I can create an release that will trigger the update on HACS. After that the new README is available in HACS.

While the pull request is not merged, we can dabber around here and tinker on stuff without interfering with the HACS configurations of users with the compass-card.

**Pull request merged**
